version: '2'
services: 
  app:
    image: php:5.6-apache
    environment:
      APACHE_RUN_USER: root
      APACHE_RUN_GROUP: root
    links:
     - db
    volumes_from:
     - data
    ports:
     - "80:80"
  data:
    image: busybox
    volumes:
     - ./src/:/app
    command: tail -f /dev/null
