version: '2'
services: 
  app:
    build: app_provision
    volumes_from:
     - data
    ports:
     - "80:80"
  data:
    image: busybox
    volumes:
     - ./src/:/var/www/html
    command: tail -f /dev/null
