version: '2'
services: 
  app:
    image: php:5.6-apache
    volumes_from:
     - data
    ports:
     - "80:80"
  data:
    image: busybox
    volumes:
     - ./src/:/var/www/html
    command: tail -f /dev/null
